// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
    D1_DATABASE: D1Database;
    API_BASE_URL: string;
    NEXTJS_ENV: string;
    LIBRARY_API_URL: string;
}
